---
abstract: 'Log::Fast for Mojolicious'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Log-Fast
provides:
  MojoX::Log::Fast:
    file: lib/MojoX/Log/Fast.pm
    version: v0.1.2
recommends:
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Perl::Critic: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
requires:
  Log::Fast: 0
  Mojolicious: 0
  perl: 5.01
  version: 0.77
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.1.2
